### PR TITLE
Add Basic Authentication

### PR DESCRIPTION
**Pull request by sydev**

### CODE REVIEW

**Comment by sydev** [comment]
After some issues with Travis CI, I added the feature for Basic Authentication.

Usage:

```javascript
const db = require('couchdb-promise')({
  baseUrl: 'http://localhost:5984',
  basicAuthentication: 'username:password'
});
```

Any suggestions?

**Comment by pmorjan** [comment]
Basic authentication should already work. Is there any difference between your PR  and this example?
```js
const db = require('couchdb-promise')({
   baseUrl: 'http://username:password@localhost:5984',
})
```
BTW, your PR contains the useless  extra file 'yarn.lock' and a change to .gitignore.
Also PR's are much better if you 'squash' multiple commits into a single commit (if possible).
In your case: 
```
git rebase -i HEAD~6
```

**Comment by dsquier** [comment]
FWIW, I'm fine with the existing implementation.

**Comment by sydev** [comment]
Ok, then I will be fine with it, too :)

**Pull request closed without merging**
